/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : CarId,
  'identifyingFeatures' : Array<string>,
  'nickname' : string,
  'country' : Country,
  'name' : string,
  'imagePrompt' : string,
}
export type CarId = bigint;
export type Country = { 'UK' : null } |
  { 'USA' : null } |
  { 'Luxury' : null } |
  { 'Russia' : null } |
  { 'Korea' : null } |
  { 'Electric' : null } |
  { 'Germany' : null } |
  { 'Japan' : null };
export interface _SERVICE {
  'getAllCars' : ActorMethod<[], Array<Car>>,
  'getCarById' : ActorMethod<[CarId], [] | [Car]>,
  'getCarsByCountry' : ActorMethod<[Country], Array<Car>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];