/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarId = IDL.Nat;
export const Country = IDL.Variant({
  'UK' : IDL.Null,
  'USA' : IDL.Null,
  'Luxury' : IDL.Null,
  'Russia' : IDL.Null,
  'Korea' : IDL.Null,
  'Electric' : IDL.Null,
  'Germany' : IDL.Null,
  'Japan' : IDL.Null,
});
export const Car = IDL.Record({
  'id' : CarId,
  'identifyingFeatures' : IDL.Vec(IDL.Text),
  'nickname' : IDL.Text,
  'country' : Country,
  'name' : IDL.Text,
  'imagePrompt' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getCarById' : IDL.Func([CarId], [IDL.Opt(Car)], ['query']),
  'getCarsByCountry' : IDL.Func([Country], [IDL.Vec(Car)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarId = IDL.Nat;
  const Country = IDL.Variant({
    'UK' : IDL.Null,
    'USA' : IDL.Null,
    'Luxury' : IDL.Null,
    'Russia' : IDL.Null,
    'Korea' : IDL.Null,
    'Electric' : IDL.Null,
    'Germany' : IDL.Null,
    'Japan' : IDL.Null,
  });
  const Car = IDL.Record({
    'id' : CarId,
    'identifyingFeatures' : IDL.Vec(IDL.Text),
    'nickname' : IDL.Text,
    'country' : Country,
    'name' : IDL.Text,
    'imagePrompt' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getCarById' : IDL.Func([CarId], [IDL.Opt(Car)], ['query']),
    'getCarsByCountry' : IDL.Func([Country], [IDL.Vec(Car)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };