/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CarId = bigint;
export interface Car {
    id: CarId;
    identifyingFeatures: Array<string>;
    nickname: string;
    country: Country;
    name: string;
    imagePrompt: string;
}
export enum Country {
    UK = "UK",
    USA = "USA",
    Luxury = "Luxury",
    Russia = "Russia",
    Korea = "Korea",
    Electric = "Electric",
    Germany = "Germany",
    Japan = "Japan"
}
export interface backendInterface {
    getAllCars(): Promise<Array<Car>>;
    getCarById(id: CarId): Promise<Car | null>;
    getCarsByCountry(country: Country): Promise<Array<Car>>;
}
import type { Car as _Car, CarId as _CarId, Country as _Country } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllCars(): Promise<Array<Car>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCars();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCars();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarById(arg0: CarId): Promise<Car | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCarsByCountry(arg0: Country): Promise<Array<Car>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarsByCountry(to_candid_Country_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarsByCountry(to_candid_Country_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Car_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Car): Car {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Country_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Country): Country {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Car]): Car | null {
    return value.length === 0 ? null : from_candid_Car_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CarId;
    identifyingFeatures: Array<string>;
    nickname: string;
    country: _Country;
    name: string;
    imagePrompt: string;
}): {
    id: CarId;
    identifyingFeatures: Array<string>;
    nickname: string;
    country: Country;
    name: string;
    imagePrompt: string;
} {
    return {
        id: value.id,
        identifyingFeatures: value.identifyingFeatures,
        nickname: value.nickname,
        country: from_candid_Country_n4(_uploadFile, _downloadFile, value.country),
        name: value.name,
        imagePrompt: value.imagePrompt
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UK: null;
} | {
    USA: null;
} | {
    Luxury: null;
} | {
    Russia: null;
} | {
    Korea: null;
} | {
    Electric: null;
} | {
    Germany: null;
} | {
    Japan: null;
}): Country {
    return "UK" in value ? Country.UK : "USA" in value ? Country.USA : "Luxury" in value ? Country.Luxury : "Russia" in value ? Country.Russia : "Korea" in value ? Country.Korea : "Electric" in value ? Country.Electric : "Germany" in value ? Country.Germany : "Japan" in value ? Country.Japan : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Car>): Array<Car> {
    return value.map((x)=>from_candid_Car_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Country_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Country): _Country {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Country): {
    UK: null;
} | {
    USA: null;
} | {
    Luxury: null;
} | {
    Russia: null;
} | {
    Korea: null;
} | {
    Electric: null;
} | {
    Germany: null;
} | {
    Japan: null;
} {
    return value == Country.UK ? {
        UK: null
    } : value == Country.USA ? {
        USA: null
    } : value == Country.Luxury ? {
        Luxury: null
    } : value == Country.Russia ? {
        Russia: null
    } : value == Country.Korea ? {
        Korea: null
    } : value == Country.Electric ? {
        Electric: null
    } : value == Country.Germany ? {
        Germany: null
    } : value == Country.Japan ? {
        Japan: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
